version: '3.1'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - mynet

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DATABASE_DSN: "postgresql://db_admin:pass5@word@postgres:5432/users?sslmode=disable"
      # "host=postgres port=5432 user=db_admin password=pass5@word dbname=users sslmode=disable timezone=uTC connect_timeout=5"
    networks:
      - mynet

    depends_on:
      - postgres

  postgres:
    image: postgres:14.0
    networks:
      - mynet
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: "db_admin"
      POSTGRES_PASSWORD: "pass5@word"
      POSTGRES_DB: "users"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data

  migrate:
    container_name: migrate
    image: migrate/migrate
    networks:
      - mynet
    volumes:
      - ./../authentication-service/migrations:/migrations

    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgresql://db_admin:pass5@word@postgres:5432/users?sslmode=disable",
        "up"
      ]
    depends_on:
      - postgres
    restart: "on-failure"

networks:
  mynet:
